In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [32]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [33]:
df.shape

(5572, 2)

In [34]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0) 

df.shape

(5572, 3)

In [35]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

Train test split

In [36]:
from sklearn.model_selection import train_test_split

# 80% training 20% testing
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2) 

In [37]:
X_train.shape

(4457,)

In [38]:
X_test.shape

(1115,)

In [39]:
X_train[:10] # 10 messages

784     You have an important customer service announc...
327                       Hi da:)how is the todays class?
208                          Aight yo, dats straight dogg
495                      Are you free now?can i call now?
2103                             Audrie lousy autocorrect
3961    I sent lanre fakeye's Eckankar details to the ...
2865    What I'm saying is if you haven't explicitly t...
2692                          Hey tmr meet at bugis 930 ?
1218    Damn, can you make it tonight or do you want t...
2494    they released another Italian one today and it...
Name: Message, dtype: object

In [40]:
y_train[:10] # nhãn tương ứng

784     1
327     0
208     0
495     0
2103    0
3961    0
2865    0
2692    0
1218    0
2494    0
Name: spam, dtype: int64

Create bag of words representation using CountVectorizer

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values) # convert text to numbers
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58883 stored elements and shape (4457, 7689)>

In [42]:
X_train_cv.toarray()[:2][0] # 2 first messages

array([0, 0, 0, ..., 0, 0, 0], shape=(7689,))

In [43]:
X_train_cv.shape

(4457, 7689)

In [44]:
v.get_feature_names_out()[1771] # word at index 1771

'chloe'

In [45]:
v.vocabulary_

{'you': 7649,
 'have': 3326,
 'an': 940,
 'important': 3605,
 'customer': 2091,
 'service': 5975,
 'announcement': 958,
 'from': 2987,
 'premier': 5331,
 'call': 1575,
 'freephone': 2957,
 '0800': 44,
 '542': 538,
 '0578': 16,
 'now': 4809,
 'hi': 3395,
 'da': 2105,
 'how': 3498,
 'is': 3726,
 'the': 6751,
 'todays': 6878,
 'class': 1800,
 'aight': 865,
 'yo': 7645,
 'dats': 2139,
 'straight': 6447,
 'dogg': 2350,
 'are': 1027,
 'free': 2949,
 'can': 1598,
 'audrie': 1113,
 'lousy': 4199,
 'autocorrect': 1122,
 'sent': 5963,
 'lanre': 3988,
 'fakeye': 2722,
 'eckankar': 2483,
 'details': 2238,
 'to': 6872,
 'mail': 4289,
 'box': 1423,
 'what': 7414,
 'saying': 5876,
 'if': 3576,
 'haven': 3328,
 'explicitly': 2685,
 'told': 6887,
 'nora': 4782,
 'know': 3934,
 'someone': 6238,
 'probably': 5380,
 'just': 3850,
 'not': 4795,
 'gonna': 3151,
 'bother': 1415,
 'hey': 3391,
 'tmr': 6868,
 'meet': 4391,
 'at': 1087,
 'bugis': 1521,
 '930': 713,
 'damn': 2114,
 'make': 4297,
 'it': 3738,
 't

In [46]:
X_train_np = X_train_cv.toarray()
X_train_np[0] # first message

array([0, 0, 0, ..., 0, 0, 0], shape=(7689,))

In [47]:
np.where(X_train_np[0]!=0) # index of non-zero elements

(array([  16,   44,  538,  940,  958, 1575, 2091, 2957, 2987, 3326, 3605,
        4809, 5331, 5975, 7649]),)

In [50]:
X_train[:4][784]

'You have an important customer service announcement from PREMIER. Call FREEPHONE 0800 542 0578 now!'

In [52]:
X_train_np[0][1575] 

np.int64(1)

Train the naive bayes model

In [53]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test) # convert text to numbers

Evaluate Performance

In [ ]:
from sklearn.metrics import classification_report

# predict test data
y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       956
           1       0.94      0.95      0.95       159

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [58]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails) #
model.predict(emails_count)

array([0, 1])

Train the model using sklearn pipeline and reduce number of lines of code

In [59]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [60]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [61]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       956
           1       0.94      0.95      0.95       159

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115

